### ISSUE TITLE
Enable/Disable Setting

### ISSUE THREAD

**Issue by eavab** [joshterrill/justin-bahn-design-extension#2]
I'd like to be able to disable and enable the extension from a setting in chrome instead of having to uninstall/reinstall the extension.

**Comment by joshterrill** [comment]
Marked this as an enhancement, and will get right on it. Thanks.

**Comment by joshterrill** [comment]
This has been fixed by https://github.com/joshterrill/justin-bahn-design-extension/commit/38260f8e84b5ce34b59498721f27f6785e277b9d you may now enable the extension by clicking on the icon on any page.
